language: python
python:

  - "2.7"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]] travis_retry pip install -rtest27_requirements.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]] travis_retry pip install -r test_requirements.txt; fi

# command to run tests
script:
   - python tests/test_manifest.py
